### ISSUE TITLE
Maps no longer persistent in newer versions of jupyter notebook

### ISSUE THREAD

**Issue by phantomas1234** [zakandrewking/escher#160] opened 2016-05-12 07:00 UTC
![image](https://cloud.githubusercontent.com/assets/55217/15206485/e4be98ae-181f-11e6-87cc-61ac583a30f4.png)

Don't really have time to narrow it down to a specific version.

**Comment by zakandrewking** [comment] 2016-05-25 22:12
That's intended behavior if you just upgraded Escher (we want to serve new versions of the maps). If you have not upgraded and they are not persisting, can you give me the output of:

```python
escher.get_cache_dir()
```

**Comment by phantomas1234** [comment] 2016-06-08 16:31
I am confused, is this really how escher is going to behave from now on? How am I supposed to create static HTML that contains the maps? Take a look at https://github.com/SBRG/GEMPro/blob/master/GEMPro_recon/Ecoli/tutorials/Temperature_Dependent_Growth_Prediction.ipynb for example (@ebrunk and @nmih check this out too). It is kinda sad that the final result doesn't show at the bottom.

**Comment by zakandrewking** [comment] 2016-06-08 18:34
Oh, I understand why you mean by persistent now. 

This is probably a bug in Escher 1.4.0 that should now be fixed in 1.4.4. Can you try out the latest version?

You may have to clear the output of the notebook, then save, and then refresh the page and the-run to get everything up-to-date.

**Comment by phantomas1234** [comment] 2016-06-08 23:08
I think it is an issue with jupyter.
![image](https://cloud.githubusercontent.com/assets/55217/15914067/3ca23a02-2dde-11e6-85fc-5a7cbe136fc7.png)
jupyter is on version 1.0.0

**Comment by zakandrewking** [comment] 2016-06-08 23:16
can you send me any error messages from the console in your Developer Tools?

**Comment by phantomas1234** [comment] 2016-06-08 23:43
Default extension for cell metadata editing loaded.
Raw Cell Format toolbar preset loaded.
Slideshow extension for metadata editing loaded.
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
load_extensions Arguments[4]
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load extension: Array[1] Error: Script error for "nbextensions/chrome-clipboard"(…)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Loading extension: jupyter-js-widgets/extension
Failed to load resource: the server responded with a status of 404 (Not Found)
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
HTML Sanitizer tr.style changed Object
HTML Sanitizer tr.style changed Object
HTML Sanitizer tr.style changed Object
HTML Sanitizer link removed Object
HTML Sanitizer div.style changed Object
HTML Sanitizer script removed Object
HTML Sanitizer link removed Object
HTML Sanitizer div.style changed Object
HTML Sanitizer script removed Object
loaded widgets
Session: kernel_created (bd4213f2-2a04-48bf-964b-12fc675c608d)
Starting WebSockets: wss://teaching.cameo.bio/user/niso/api/kernels/c20a40df-816a-4cc4-adbd-0bdef4484541
Kernel: kernel_connected (c20a40df-816a-4cc4-adbd-0bdef4484541)
Kernel: kernel_ready (c20a40df-816a-4cc4-adbd-0bdef4484541)
Widget backend and frontend versions are compatible
Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'https://teaching.cameo.bio' is therefore not allowed access.

**Comment by phantomas1234** [comment] 2016-06-08 23:47
Is it maybe the font issue at the end?

**Comment by phantomas1234** [comment] 2016-06-08 23:50
Yeah tried it also locally (where none of the other issues occur). Looks like there is some issue with some CDN or something? 
![image](https://cloud.githubusercontent.com/assets/55217/15914856/994637d0-2de4-11e6-992c-bac994d8c42d.png)

**Comment by zakandrewking** [comment] 2016-09-14 18:35
Are you still seeing this? If fonts are not loading, that would not usually crash the whole map. Can you recreate it in a fresh notebook?

**Comment by phantomas1234** [comment] 2016-09-14 22:27
Yes, please check for yourself here: https://github.com/biosustain/cell-factory-design-course/blob/master/03-Pathway-visualization.ipynb
As you can the notebook was created about 7 days ago.

**Comment by phantomas1234** [comment] 2016-09-14 22:30
Yes, check this notebook for example: https://github.com/biosustain/cell-factory-design-course/blob/master/03-Pathway-visualization.ipynb
It was created about 7 days ago. If you inspect the pathway viz div there seems to be nothing. You don't have this problem? Check also the last output cell of this notebooke here: https://github.com/SBRG/GEMPro/blob/master/GEMPro_recon/Ecoli/tutorials/Temperature_Dependent_Growth_Prediction.ipynb it is older though

**Comment by zakandrewking** [comment] 2016-09-15 15:37
I haven't solved this yet, but I did find that NBViewer and Github display the notebooks differently. To test, I downloaded that first notebook, ran the cells locally, saved, and uploaded as a Gist.

Doesn't render:
https://gist.github.com/zakandrewking/1fbca738a4d5f193bc2d97b78740632b

Renders:
http://nbviewer.jupyter.org/gist/zakandrewking/1fbca738a4d5f193bc2d97b78740632b

The first version doesn't even try to render the maps, from what I can tell.

**Comment by zakandrewking** [comment] 2016-09-15 15:44
I have seen others mention that we should contact GitHub support, so I'll do that.

**Comment by phantomas1234** [comment] 2016-09-22 14:35
Ok, I think I finally figured this one out. I think there is a problem with trusted notebooks. After trusting the notebook the maps work. Check out the this screen capture https://www.dropbox.com/s/brkv3ilawmo4lof/escher_trust_notebook.mov?dl=0 This doesn't really explain though why your notebook works on nbviewer and ours don't but at least I think we know now where to look at.

**Comment by phantomas1234** [comment] 2016-09-22 14:50
This provides some context for the new jupyter notebook security model https://jupyter-notebook.readthedocs.io/en/latest/security.html

**Comment by zakandrewking** [comment] 2016-09-23 22:44
very interesting. thanks for figuring this out.

I also emailed GitHub, but I haven't heard back yet. I'll leave this open
until I do.

**Closed** 2018-02-20 17:40 UTC
